version: "3.9"

services:
  python-env:
    build: .
    container_name: python-env
    network_mode: host   # uses the host's network stack
    stdin_open: true     # keep STDIN open (useful for interactive mode)
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
      - MPLBACKEND=TkAgg
    tty: true            # allocate a pseudo-TTY
    volumes:
      - ../:/app           # mount current directory into /app
    working_dir: /app
    command: /bin/bash  